# Generated by Django 4.2.11 on 2026-04-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="category",
            field=models.CharField(
                choices=[
                    ("movie", "Movie"),
                    ("cartoon", "Cartoon"),
                    ("bollywood", "Bollywood"),
                    ("series", "Series"),
                ],
                default="movie",
                max_length=20,
            ),
        ),
    ]
